services:
  backend:
    build:
      context: ./backend
    container_name: streaming-backend
    env_file:
      - ./backend/.env
    environment:
      NEO4J_SEED_ON_START: "true"
      FRONTEND_PATH: "/frontend"
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/frontend:ro
      - ./backend/backend/media:/app/backend/media
